---
fr:
  results:
    critical_failure: Echec critique
    failure: Echec
    success: Réussite
    critical_success: Réussite critique

  texts:
    header1: Remplacer un d20 par 2d10
    intro1: Cette methode permet de remplacer un d20 par 2d10. Elle est utile pour ceux qui trouvent le d20 trop aléatoire et qui souhaitent avoir un jet plus "moyenné".
    desc1: "La méthode est simple : lancez 2d10 et sommez le résultat des deux dés. Si la somme est <b>strictement supérieure</b> à la difficultée, alors le résultat est une réussite. Sinon, c'est un echec."
    desc2: De plus, si le résultat est un double, considérez le résultat comme un critique (échec critique s'il s'agissait d'un échec, réussite critique s'il s'agissait d'une réussite).